@host = http://localhost:3000


#############################################################
######PRUEBAS DE CLIENTES######################################

### Crear cliente
POST {{host}}/customers HTTP/1.1
Content-Type: application/json

{
    "firstname": "Pedro",
    "lastname": "Ccente",
    "email": "pedroz@email.com",
    "phone": "555-456",
    "address": "Calle 123",
    "isActive": true
}

### Listar todos los clientes
GET {{host}}/customers HTTP/1.1

### Listar solo clientes activos
GET {{host}}/customers/active HTTP/1.1

### Listar solo clientes dados de baja (inactivos)
GET {{host}}/customers/inactive HTTP/1.1

### Listar por ID un cliente
GET {{host}}/customers/28920c35-9e9b-4382-9676-408b34861d86 HTTP/1.1

### Actualizar cliente
PATCH {{host}}/customers/28920c35-9e9b-4382-9676-408b34861d86 HTTP/1.1
Content-Type: application/json

{
    "id": "28920c35-9e9b-4382-9676-408b34861d86",
    "firstname": "Juan Carlos",
    "lastname": "Pérez",
    "email": "juan.carlos@email.com",
    "phone": "555-9876",
    "address": "Av. Central 456"
}

### Soft Delete (desactivar cliente)
PATCH {{host}}/customers/deactivate/28920c35-9e9b-4382-9676-408b34861d86 HTTP/1.1

### RESTaURAR 
PATCH {{host}}/customers/activate/28920c35-9e9b-4382-9676-408b34861d86 HTTP/1.1

### Remover cliente (eliminación física y permanente)
DELETE {{host}}/customers/28920c35-9e9b-4382-9676-408b34861d86 HTTP/1.1
###



#############################################################
#PRUEBA DE CATEGORIAS###########################################

### Crear categoria
POST {{host}}/categories HTTP/1.1
Content-Type: application/json

{
    "name": "Tortas de bodas",
    "description": "especialidad de la casa",
    "isActive": true
}

### Listar todos los categorias
GET {{host}}/categories HTTP/1.1

### Listar solo  activos
GET {{host}}/categories/active HTTP/1.1

### Listar solo  dados de baja (inactivos)
GET {{host}}/categories/inactive HTTP/1.1

### Listar por ID 
GET {{host}}/categories/8 HTTP/1.1

### Actualizar una Categoria
PATCH {{host}}/categories/8 HTTP/1.1
Content-Type: application/json

{
    "id": 8,
    "name": "torta actualizada ",
    "description": "Descripcion actualizada"
}
### Soft Delete
PATCH {{host}}/categories/deactivate/8 HTTP/1.1

### Activar  (Restaurar  dado de baja)
PATCH {{host}}/categories/activate/8 HTTP/1.1

### Remover  (Eliminación física y permanente)
DELETE {{host}}/categories/8 HTTP/1.1
###




#############################################################
######PRUEBAS DE PRODUCTOS#####################################3

### Crear producto
POST {{host}}/products HTTP/1.1
Content-Type: application/json

{
    "name": "Torta pequeña ",
    "description": "",
    "price": 1.5,
    "stock": 10,
    "categoryId": 9,
    "isActive": true
}
### Listar todos los productos
GET {{host}}/products HTTP/1.1

### Listar solo  activos
GET {{host}}/products/active HTTP/1.1

### Listar solo productos dados de baja (inactivos)
GET {{host}}/products/inactive HTTP/1.1

### Listar por ID un producto
GET {{host}}/products/305ca8c2-c298-4005-917b-833f775d127f HTTP/1.1

### Actualizar producto
PATCH {{host}}/products/b7b076f1-378b-47f9-96ec-85b9c17f7cdf HTTP/1.1
Content-Type: application/json

{
    "id": "b7b076f1-378b-47f9-96ec-85b9c17f7cdf",
    "name": "Producto actualizado",
    "description": "Descripcion del producto 1 actualizada",
    "price": 100,
    "stock": 20,
    "categoryId": 9
}
### Soft Delete
PATCH {{host}}/products/deactivate/305ca8c2-c298-4005-917b-833f775d127f HTTP/1.1

### Activar producto (Restaurar producto dado de baja)
PATCH {{host}}/products/activate/305ca8c2-c298-4005-917b-833f775d127f HTTP/1.1

### Remover producto (Eliminación física y permanente)
DELETE {{host}}/products/305ca8c2-c298-4005-917b-833f775d127f HTTP/1.1
###

